name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v2
      #- uses: akhileshns/heroku-deploy@v3.0.0
      name: Wait for Render Deployment
      uses: bounceapp/render-action@0.2.0
      run : npm install
            npm start 
        with:
          #heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          #heroku_app_name: "bike-helper"
          #heroku_email: "hmlu36@gmail.com"
          #usedocker: false
          email: "hmlu36@gmail.com"
          password: ${{ secrets.RENDER_PASSWORD }}
          token: ${{ secrets.GITHUB_TOKEN }}
          service-id: srv-cc61a3la49936rk9l9og